---
name: "Code Quality: Link Checker"

on:
  push:
  pull_request:

jobs:
  linkchecker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.5.4
        with:
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
